'use strict';
const fs = require('fs');
const path = require('path');
const assert = require('assert');
const root = path.join(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'admin/customers.html'), 'utf8');
const js = fs.readFileSync(path.join(root, 'assets/js/admin-customers.js'), 'utf8');
const sql = fs.readFileSync(path.join(root, 'supabase/admin-customers.sql'), 'utf8');

assert.match(js, /from\('profiles'\)[\s\S]*\.eq\('role', 'customer'\)/, 'loads only customer profiles');
for (const field of ['full_name', 'company_name', 'phone', 'account_status', 'created_at']) assert.ok(js.includes(field), `renders ${field}`);
assert.match(js, /adm-search[\s\S]*oninput/); assert.match(js, /adm-f-status[\s\S]*onchange/); assert.match(js, /PAGE_SIZE/);
for (const table of ['quotes', 'holds', 'inspections', 'enquiries']) assert.ok(js.includes(`'${table}'`), `loads ${table}`);
assert.match(js, /rpc\('admin_set_customer_status'/, 'status changes use the RPC');
assert.ok(js.indexOf('row.account_status = newStatus') > js.indexOf("rpc('admin_set_customer_status'"), 'UI changes only after RPC returns');
assert.doesNotMatch(html + js, /NGD_DEMO_CUSTOMERS|customers-data\.js|enquiries-data\.js|password/i, 'no demo records or sensitive auth fields');
assert.match(sql, /alter table public\.profiles enable row level security/);
assert.match(sql, /auth\.uid\(\) is null or not public\.is_active_admin\(\)/);
assert.match(sql, /new_status not in \('active', 'inactive', 'suspended'\)/);
assert.match(sql, /where id = target_user_id\s+and role = 'customer'/, 'RPC cannot target an admin');
assert.doesNotMatch(sql, /set\s+role\s*=/i, 'RPC never changes a role');
assert.match(sql, /revoke update on public\.profiles from authenticated/);
assert.match(sql, /using \(role = 'customer' and public\.is_active_admin\(\)\)/);
console.log('PASS  Admin Customers uses real Supabase data and secure status RPC');
