/**
 * The full-details dialog's words, in the three languages (see
 * src/i18n/useCopy.js).
 *
 * Trade terms follow src/i18n/glossary.md; the grade rows that match a
 * dictionary term (shape, carat, cut, colour…) read it from `terms`. Grades,
 * lab names, stock, report and certificate numbers, prices, "ct", "360°" and
 * "WhatsApp" are never translated.
 *
 * `availability` is keyed by the value stored on the stone ('In Stock'…),
 * which stays English everywhere it is matched; only what is shown changes. A
 * value not listed here is shown as stored.
 */
export default {
  en: {
    views: {
      photo: 'Photograph',
      spin: '360° view',
      top: 'Top view',
      side: 'Side view',
      size: 'Size',
      cert: 'Certificate',
    },
    rows: {
      stockNo: 'Stock No.',
      location: 'Location',
      reportNo: 'Report No.',
      table: 'Table',
      depth: 'Depth',
      ratio: 'Ratio',
      measurements: 'Measurements',
      growth: 'Growth',
      certificateNo: 'Certificate No.',
      availability: 'Availability',
      total: 'Total',
      perCarat: 'Per carat',
    },
    availability: {
      'In Stock': 'In Stock',
      'On Request': 'On Request',
      Reserved: 'Reserved',
      Sold: 'Sold',
    },
    title: '{ct} carat {shape} diamond, {stock}',
    eyebrow: 'Diamond view',
    summary: 'Summary',
    sections: {
      details: 'Diamond details',
      grading: 'Grading',
      measurement: 'Measurement',
      more: 'Additional information',
    },
    failed: 'The full record could not be loaded just now. The grades above are current; ask the desk for the rest.',
    media: 'Diamond media',
    zoomIn: 'Zoom in',
    zoomOut: 'Zoom out',
    photoAlt: '{shape} diamond {stock}',
    hintZoom: 'Click to zoom',
    hintZoomOut: 'Click to zoom out',
    reportFor: 'Grading report for {stock}',
    viewsLabel: 'Views',
    cert: {
      title: 'Diamond certificate',
      laboratory: 'Laboratory',
      verify: 'Verify on {lab}',
      copied: 'Report number copied',
      copy: 'Copy report number',
      open: 'Open the full report',
      framedTitle: 'The report opens on {lab}',
      framedBody: 'Grading laboratories do not allow their reports to be shown inside another site. Opening it on their own page is also what makes it proof — the record you read is the laboratory’s, not a copy of ours.',
      framedOpen: 'Open report {number} on {lab}',
      missing: 'The report document is not attached online for this stone.',
      request: 'Request the certificate',
    },
    inSelection: 'In your selection ✓',
    add: 'Add to selection +',
    saved: 'Saved',
    save: 'Save to wishlist',
    loading: 'Loading',
  },

  hi: {
    views: {
      photo: 'फ़ोटो',
      spin: '360° व्यू',
      top: 'टॉप व्यू',
      side: 'साइड व्यू',
      size: 'साइज़',
      cert: 'सर्टिफिकेट',
    },
    rows: {
      stockNo: 'स्टॉक नं.',
      location: 'स्थान',
      reportNo: 'रिपोर्ट नं.',
      table: 'टेबल',
      depth: 'डेप्थ',
      ratio: 'रेशियो',
      measurements: 'मेज़रमेंट',
      growth: 'ग्रोथ',
      certificateNo: 'सर्टिफिकेट नं.',
      availability: 'उपलब्धता',
      total: 'कुल',
      perCarat: 'प्रति कैरेट',
    },
    availability: {
      'In Stock': 'उपलब्ध',
      'On Request': 'पूछताछ पर',
      Reserved: 'रिज़र्व',
      Sold: 'बिक गया',
    },
    title: '{ct} कैरेट {shape} हीरा, {stock}',
    eyebrow: 'डायमंड व्यू',
    summary: 'सारांश',
    sections: {
      details: 'हीरे का विवरण',
      grading: 'ग्रेडिंग',
      measurement: 'माप',
      more: 'अतिरिक्त जानकारी',
    },
    failed: 'पूरा रिकॉर्ड अभी लोड नहीं हो सका। ऊपर दिए गए ग्रेड मौजूदा हैं; बाकी जानकारी के लिए डेस्क से पूछें।',
    media: 'हीरे का मीडिया',
    zoomIn: 'ज़ूम इन करें',
    zoomOut: 'ज़ूम आउट करें',
    photoAlt: '{shape} हीरा {stock}',
    hintZoom: 'ज़ूम करने के लिए क्लिक करें',
    hintZoomOut: 'ज़ूम आउट करने के लिए क्लिक करें',
    reportFor: '{stock} की ग्रेडिंग रिपोर्ट',
    viewsLabel: 'व्यू',
    cert: {
      title: 'हीरे का सर्टिफिकेट',
      laboratory: 'लैब',
      verify: '{lab} पर जाँचें',
      copied: 'रिपोर्ट नंबर कॉपी हो गया',
      copy: 'रिपोर्ट नंबर कॉपी करें',
      open: 'पूरी रिपोर्ट खोलें',
      framedTitle: 'रिपोर्ट {lab} पर खुलेगी',
      framedBody: 'ग्रेडिंग लैब अपनी रिपोर्ट किसी दूसरी साइट के अंदर दिखाने की अनुमति नहीं देतीं। उनके अपने पेज पर खोलना ही इसे प्रमाण बनाता है — आप जो रिकॉर्ड पढ़ते हैं वह लैब का होता है, हमारी नकल नहीं।',
      framedOpen: 'रिपोर्ट {number} को {lab} पर खोलें',
      missing: 'इस हीरे की रिपोर्ट ऑनलाइन अटैच नहीं की गई है।',
      request: 'सर्टिफिकेट मँगवाएँ',
    },
    inSelection: 'आपके चयन में ✓',
    add: 'चयन में जोड़ें +',
    saved: 'सहेजा गया',
    save: 'विशलिस्ट में सहेजें',
    loading: 'लोड हो रहा है',
  },

  gu: {
    views: {
      photo: 'ફોટો',
      spin: '360° વ્યૂ',
      top: 'ટોપ વ્યૂ',
      side: 'સાઇડ વ્યૂ',
      size: 'સાઇઝ',
      cert: 'સર્ટિફિકેટ',
    },
    rows: {
      stockNo: 'સ્ટોક નં.',
      location: 'સ્થળ',
      reportNo: 'રિપોર્ટ નં.',
      table: 'ટેબલ',
      depth: 'ડેપ્થ',
      ratio: 'રેશિયો',
      measurements: 'મેઝરમેન્ટ',
      growth: 'ગ્રોથ',
      certificateNo: 'સર્ટિફિકેટ નં.',
      availability: 'ઉપલબ્ધતા',
      total: 'કુલ',
      perCarat: 'પ્રતિ કેરેટ',
    },
    availability: {
      'In Stock': 'ઉપલબ્ધ',
      'On Request': 'પૂછપરછ પર',
      Reserved: 'રિઝર્વ',
      Sold: 'વેચાયેલ',
    },
    title: '{ct} કેરેટ {shape} હીરો, {stock}',
    eyebrow: 'ડાયમંડ વ્યૂ',
    summary: 'સારાંશ',
    sections: {
      details: 'હીરાની વિગતો',
      grading: 'ગ્રેડિંગ',
      measurement: 'માપ',
      more: 'વધારાની માહિતી',
    },
    failed: 'પૂરો રેકોર્ડ હમણાં લોડ થઈ શક્યો નથી. ઉપર આપેલા ગ્રેડ હાલના છે; બાકીની માહિતી માટે ડેસ્કને પૂછો.',
    media: 'હીરાનું મીડિયા',
    zoomIn: 'ઝૂમ ઇન કરો',
    zoomOut: 'ઝૂમ આઉટ કરો',
    photoAlt: '{shape} હીરો {stock}',
    hintZoom: 'ઝૂમ કરવા માટે ક્લિક કરો',
    hintZoomOut: 'ઝૂમ આઉટ કરવા માટે ક્લિક કરો',
    reportFor: '{stock} માટે ગ્રેડિંગ રિપોર્ટ',
    viewsLabel: 'વ્યૂ',
    cert: {
      title: 'હીરાનું સર્ટિફિકેટ',
      laboratory: 'લેબ',
      verify: '{lab} પર ચકાસો',
      copied: 'રિપોર્ટ નંબર કૉપિ થઈ ગયો',
      copy: 'રિપોર્ટ નંબર કૉપિ કરો',
      open: 'પૂરી રિપોર્ટ ખોલો',
      framedTitle: 'રિપોર્ટ {lab} પર ખૂલશે',
      framedBody: 'ગ્રેડિંગ લેબ પોતાની રિપોર્ટ બીજી સાઇટની અંદર બતાવવા દેતી નથી. તેમના પોતાના પેજ પર ખોલવું જ તેને પુરાવો બનાવે છે — તમે જે રેકોર્ડ વાંચો છો તે લેબનો છે, અમારી નકલ નહીં.',
      framedOpen: 'રિપોર્ટ {number} {lab} પર ખોલો',
      missing: 'આ હીરાની રિપોર્ટ ઓનલાઇન જોડવામાં આવી નથી.',
      request: 'સર્ટિફિકેટ મંગાવો',
    },
    inSelection: 'તમારી પસંદગીમાં ✓',
    add: 'પસંદગીમાં ઉમેરો +',
    saved: 'સાચવ્યું',
    save: 'વિશલિસ્ટમાં સાચવો',
    loading: 'લોડ થઈ રહ્યું છે',
  },
};
