import LegalLayout, { H } from './LegalLayout.jsx';
import styles from './LegalPage.module.css';

/**
 * Privacy Policy.
 *
 * THE WORDING IS THE OWNER'S, UNCHANGED. Every sentence below is the policy
 * New Grown Diamond supplied, in its order, with its capitalised defined terms
 * and its own date. Only the presentation is ours: headings become anchors, the
 * definitions become a definition list, and the lists become lists. Nothing is
 * paraphrased, shortened or added — a privacy policy is a legal statement, and
 * the one place on the site where a helpful rewording would be a change of
 * meaning.
 *
 * The contents list follows the reader: the section on screen is marked in it
 * as the page scrolls, and every heading can be linked to directly.
 */

const LAST_UPDATED = 'December 23, 2022';
const EMAIL = 'newgrowndiamonds@gmail.com';

const TOC = [
  { id: 'interpretation-and-definitions', label: 'Interpretation and Definitions' },
  { id: 'collecting-and-using', label: 'Collecting and Using Your Personal Data' },
  { id: 'types-of-data', label: 'Types of Data Collected', sub: true },
  { id: 'use-of-data', label: 'Use of Your Personal Data', sub: true },
  { id: 'retention', label: 'Retention of Your Personal Data', sub: true },
  { id: 'transfer', label: 'Transfer of Your Personal Data', sub: true },
  { id: 'disclosure', label: 'Disclosure of Your Personal Data', sub: true },
  { id: 'security', label: 'Security of Your Personal Data', sub: true },
  { id: 'childrens-privacy', label: "Children's Privacy" },
  { id: 'links', label: 'Links to Other Websites' },
  { id: 'changes', label: 'Changes to this Privacy Policy' },
  { id: 'contact', label: 'Contact Us' },
];

const DEFINITIONS = [
  ['Account', 'means a unique account created for You to access our Service or parts of our Service.'],
  ['Affiliate', 'means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.'],
  ['Application', 'means the software program provided by the Company downloaded by You on any electronic device, named New Grown Diamonds.'],
  ['Company', '(referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to New Grown Diamonds.'],
  ['Device', 'means any device that can access the Service such as a computer, a cellphone or a digital tablet.'],
  ['Personal Data', 'is any information that relates to an identified or identifiable individual.'],
  ['Service', 'refers to the Application.'],
  ['Service Provider', 'means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.'],
  ['Usage Data', 'refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).'],
  ['You', 'means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.'],
];

const PURPOSES = [
  ['To provide and maintain our Service', ', including to monitor the usage of our Service.'],
  ['To manage Your Account:', ' to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.'],
  ['For the performance of a contract:', ' the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.'],
  ['To contact You:', ' To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application\'s push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.'],
  ['To provide You', ' with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.'],
  ['To manage Your requests:', ' To attend and manage Your requests to Us.'],
  ['For business transfers:', ' We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.'],
  ['For other purposes:', ' We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.'],
];

const SHARING = [
  ['With Service Providers:', ' We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.'],
  ['For business transfers:', ' We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.'],
  ['With Affiliates:', ' We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.'],
  ['With business partners:', ' We may share Your information with Our business partners to offer You certain products, services or promotions.'],
  ['With other users:', ' when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.'],
  ['With Your consent:', ' We may disclose Your personal information for any other purpose with Your consent.'],
];

const LEGAL = [
  'Comply with a legal obligation',
  'Protect and defend the rights or property of the Company',
  'Prevent or investigate possible wrongdoing in connection with the Service',
  'Protect the personal safety of Users of the Service or the public',
  'Protect against legal liability',
];

export default function PrivacyPage() {
  return (
    <LegalLayout
      title={<>Privacy <em>Policy</em></>}
      updated={{ label: LAST_UPDATED, iso: '2022-12-23' }}
      toc={TOC}
      lead={
        <>
          <p>
            This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your
            information when You use the Service and tells You about Your privacy rights and how the law protects You.
          </p>
          <p>
            We use Your Personal data to provide and improve the Service. By using the Service, You agree to the
            collection and use of information in accordance with this Privacy Policy.
          </p>
        </>
      }
    >
      {/* ---------------- Interpretation and Definitions ---------------- */}
      <section aria-labelledby="interpretation-and-definitions">
        <H id="interpretation-and-definitions">Interpretation and Definitions</H>
        <H as="h3" id="interpretation">Interpretation</H>
        <p>
          The words of which the initial letter is capitalized have meanings defined under the following
          conditions. The following definitions shall have the same meaning regardless of whether they appear in
          singular or in plural.
        </p>
        <H as="h3" id="definitions">Definitions</H>
        <p>For the purposes of this Privacy Policy:</p>
        <dl className={styles.defs}>
          {DEFINITIONS.map(([term, text]) => (
            <div key={term}>
              <dt>{term}</dt>
              <dd>{text}</dd>
            </div>
          ))}
        </dl>
      </section>

      {/* ---------------- Collecting and Using ---------------- */}
      <section aria-labelledby="collecting-and-using">
        <H id="collecting-and-using">Collecting and Using Your Personal Data</H>

        <H as="h3" id="types-of-data">Types of Data Collected</H>
        <H as="h4" id="personal-data">Personal Data</H>
        <p>
          While using Our Service, We may ask You to provide Us with certain personally identifiable information
          that can be used to contact or identify You. Personally identifiable information may include, but is not
          limited to:
        </p>
        <ul className={styles.list}>
          <li>Email address</li>
          <li>First name and last name</li>
          <li>Phone number</li>
          <li>Address, State, Province, ZIP/Postal code, City</li>
          <li>Usage Data</li>
        </ul>

        <H as="h4" id="usage-data">Usage Data</H>
        <p>Usage Data is collected automatically when using the Service.</p>
        <p>
          Usage Data may include information such as Your Device&apos;s Internet Protocol address (e.g. IP
          address), browser type, browser version, the pages of our Service that You visit, the time and date of
          Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
        </p>
        <p>
          When You access the Service by or through a mobile device, We may collect certain information
          automatically, including, but not limited to, the type of mobile device You use, Your mobile device
          unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet
          browser You use, unique device identifiers and other diagnostic data.
        </p>
        <p>
          We may also collect information that Your browser sends whenever You visit our Service or when You access
          the Service by or through a mobile device.
        </p>

        <H as="h4" id="application-data">Information Collected while Using the Application</H>
        <p>
          While using Our Application, in order to provide features of Our Application, We may collect, with Your
          prior permission:
        </p>
        <ul className={styles.list}>
          <li>Pictures and other information from your Device&apos;s camera and photo library</li>
        </ul>
        <p>
          We use this information to provide features of Our Service, to improve and customize Our Service. The
          information may be uploaded to the Company&apos;s servers and/or a Service Provider&apos;s server or it
          may be simply stored on Your device.
        </p>
        <p>You can enable or disable access to this information at any time, through Your Device settings.</p>

        <H as="h3" id="use-of-data">Use of Your Personal Data</H>
        <p>The Company may use Personal Data for the following purposes:</p>
        <ul className={styles.list}>
          {PURPOSES.map(([lead, rest]) => (
            <li key={lead}><strong>{lead}</strong>{rest}</li>
          ))}
        </ul>
        <p>We may share Your personal information in the following situations:</p>
        <ul className={styles.list}>
          {SHARING.map(([lead, rest]) => (
            <li key={lead}><strong>{lead}</strong>{rest}</li>
          ))}
        </ul>

        <H as="h3" id="retention">Retention of Your Personal Data</H>
        <p>
          The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in
          this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our
          legal obligations (for example, if we are required to retain your data to comply with applicable laws),
          resolve disputes, and enforce our legal agreements and policies.
        </p>
        <p>
          The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained
          for a shorter period of time, except when this data is used to strengthen the security or to improve the
          functionality of Our Service, or We are legally obligated to retain this data for longer time periods.
        </p>

        <H as="h3" id="transfer">Transfer of Your Personal Data</H>
        <p>
          Your information, including Personal Data, is processed at the Company&apos;s operating offices and in any
          other places where the parties involved in the processing are located. It means that this information may
          be transferred to — and maintained on — computers located outside of Your state, province, country or other
          governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.
        </p>
        <p>
          Your consent to this Privacy Policy followed by Your submission of such information represents Your
          agreement to that transfer.
        </p>
        <p>
          The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in
          accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an
          organization or a country unless there are adequate controls in place including the security of Your data
          and other personal information.
        </p>

        <H as="h3" id="disclosure">Disclosure of Your Personal Data</H>
        <H as="h4" id="business-transactions">Business Transactions</H>
        <p>
          If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred.
          We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy
          Policy.
        </p>
        <H as="h4" id="law-enforcement">Law enforcement</H>
        <p>
          Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do
          so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
        </p>
        <H as="h4" id="other-legal-requirements">Other legal requirements</H>
        <p>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
        <ul className={styles.list}>
          {LEGAL.map((l) => <li key={l}>{l}</li>)}
        </ul>

        <H as="h3" id="security">Security of Your Personal Data</H>
        <p>
          The security of Your Personal Data is important to Us, but remember that no method of transmission over
          the Internet, or method of electronic storage is 100% secure. While We strive to use commercially
          acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
        </p>
      </section>

      {/* ---------------- Children's Privacy ---------------- */}
      <section aria-labelledby="childrens-privacy">
        <H id="childrens-privacy">Children&apos;s Privacy</H>
        <p>
          Our Service does not address anyone under the age of 13. We do not knowingly collect personally
          identifiable information from anyone under the age of 13. If You are a parent or guardian and You are
          aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We
          have collected Personal Data from anyone under the age of 13 without verification of parental consent, We
          take steps to remove that information from Our servers.
        </p>
        <p>
          If We need to rely on consent as a legal basis for processing Your information and Your country requires
          consent from a parent, We may require Your parent&apos;s consent before We collect and use that
          information.
        </p>
      </section>

      {/* ---------------- Links ---------------- */}
      <section aria-labelledby="links">
        <H id="links">Links to Other Websites</H>
        <p>
          Our Service may contain links to other websites that are not operated by Us. If You click on a third
          party link, You will be directed to that third party&apos;s site. We strongly advise You to review the
          Privacy Policy of every site You visit.
        </p>
        <p>
          We have no control over and assume no responsibility for the content, privacy policies or practices of
          any third party sites or services.
        </p>
      </section>

      {/* ---------------- Changes ---------------- */}
      <section aria-labelledby="changes">
        <H id="changes">Changes to this Privacy Policy</H>
        <p>
          We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new
          Privacy Policy on this page.
        </p>
        <p>
          We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming
          effective and update the &quot;Last updated&quot; date at the top of this Privacy Policy.
        </p>
        <p>
          You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy
          are effective when they are posted on this page.
        </p>
      </section>

      {/* ---------------- Contact ---------------- */}
      <section aria-labelledby="contact" className={styles.contact}>
        <H id="contact">Contact Us</H>
        <p>If you have any questions about this Privacy Policy, You can contact us:</p>
        <ul className={styles.list}>
          <li>By email: <a href={`mailto:${EMAIL}?subject=${encodeURIComponent('Privacy Policy question')}`}>{EMAIL}</a></li>
        </ul>
      </section>
    </LegalLayout>
  );
}
