import { TOPIC_LABEL } from '@/lib/supabase/queries/feedback.js';

/**
 * The feedback components' words, in the three languages (see
 * src/i18n/useCopy.js). One file for the parts that share Feedback.module.css:
 * FeedbackForm, ArticleForm, FeedbackWall and Stars; the feedback page takes
 * its topic labels from here too.
 *
 * STORED VALUES STAY ENGLISH. A topic's key ('service', 'journal') is what
 * goes into the enquiry subject and is parsed back later, so only the label
 * is translated — and the English labels are the lib's own TOPIC_LABEL, which
 * the Control Centre also shows. What a visitor typed (names, cities, their
 * words) is always shown as they wrote it.
 *
 * `errors` is keyed by the `reason` a refused send carries
 * (lib/supabase/queries/feedback.js); the English sentences are the lib's own.
 */
export default {
  en: {
    topics: TOPIC_LABEL,
    on: 'On “{title}”',
    stars: {
      shown: '{n} out of 5',
      legend: 'Your rating',
      one: '{n} star — {word}',
      many: '{n} stars — {word}',
      words: ['', 'Poor', 'Fair', 'Good', 'Very good', 'Excellent'],
      choose: 'Choose a rating',
    },
    errors: {
      email: 'That email address does not look right. Check it and try again.',
      message: 'Please write a little more — at least 20 characters.',
      name: 'Please enter your name.',
      session: 'Please sign in again, or sign out and send it as a guest.',
      failed: 'It could not be sent just now. Please try again in a moment.',
      unconfigured: 'This deployment is not connected to its database.',
    },
    optional: 'optional',
    email: 'Email',
    sending: 'Sending…',
    feedback: {
      sent: {
        title: 'Thank you',
        note: 'Your feedback is with our team. It appears on the website once it has been reviewed.',
        noteSignedIn: 'Your feedback is with our team. It appears on the website once it has been reviewed — you can follow it on the feedback page.',
        again: 'Write another',
      },
      invalid: {
        rating: 'Choose a rating from one to five stars.',
        messageShort: 'Write at least {n} characters.',
        messageLong: 'Keep it under {n} characters.',
        name: 'Enter the name to show beside your feedback.',
        nameLong: 'Keep the name under {n} characters.',
        email: 'Enter an email address we can reply to.',
        cityLong: 'Keep the city under {n} characters.',
        consent: 'Please confirm your feedback may be shown on the website.',
      },
      limit: 'You have sent a lot of feedback today — thank you. Please send any more tomorrow.',
      about: 'About “{title}”',
      topic: 'What is it about?',
      message: 'Your feedback',
      placeholder: 'What went well, and what could be better?',
      left: '{n} characters left',
      over: '{n} over the limit',
      name: 'Name to show',
      city: 'City',
      emailNote: 'never shown — only so we can reply',
      consent: 'Once reviewed, my feedback may be shown on this website with the name and city above. My email is never shown.',
      send: 'Send feedback',
      account: 'Sent from your account.',
      guestLead: 'No account needed · ',
      guestLink: 'sign in',
      guestTail: ' to follow its status.',
    },
    article: {
      sent: {
        title: 'Thank you for writing',
        noteTo: 'Your article is with our editors. If it is right for the journal we will write to {email} before anything is published — we may suggest edits and ask for a photograph.',
        noteYou: 'Your article is with our editors. If it is right for the journal we will write to you before anything is published — we may suggest edits and ask for a photograph.',
        again: 'Send another',
      },
      invalid: {
        name: 'Enter your name, as it should appear with the article.',
        email: 'Enter an email address we can reply to.',
        title: 'Give your article a title.',
        titleLong: 'Keep the title under {n} characters.',
        summaryLong: 'Keep the summary under {n} characters.',
        bodyShort: 'An article needs at least {n} characters.',
        bodyLong: 'Keep it under {n} characters.',
        consent: 'Please confirm the article is yours to share.',
      },
      limit: 'You have sent three articles today — thank you. Please send any more tomorrow.',
      about: 'For the NGD journal',
      title: 'Article title',
      summary: 'Summary',
      summaryNote: 'optional — one or two sentences',
      body: 'Your article',
      placeholder: 'Write or paste your article. Leave a blank line between paragraphs.',
      wordOne: '{n} word',
      wordMany: '{n} words',
      name: 'Your name',
      emailNote: 'never published',
      consent: 'I wrote this article and New Grown Diamond may edit it and publish it on its journal with my name. Nothing is published before the team contacts me.',
      send: 'Send article',
      quiet: 'Read by our editors before anything goes live.',
    },
  },

  hi: {
    topics: {
      general: 'सामान्य',
      diamonds: 'हीरे',
      jewellery: 'ज्वेलरी',
      service: 'सेवा',
      website: 'यह वेबसाइट',
      journal: 'जर्नल',
    },
    on: '“{title}” पर',
    stars: {
      shown: '5 में से {n}',
      legend: 'आपकी रेटिंग',
      one: '{n} स्टार — {word}',
      many: '{n} स्टार — {word}',
      words: ['', 'खराब', 'ठीक-ठाक', 'अच्छा', 'बहुत अच्छा', 'बेहतरीन'],
      choose: 'रेटिंग चुनें',
    },
    errors: {
      email: 'यह ईमेल पता सही नहीं लग रहा। इसे जाँचकर फिर से कोशिश करें।',
      message: 'कृपया थोड़ा और लिखें — कम से कम 20 अक्षर।',
      name: 'कृपया अपना नाम लिखें।',
      session: 'कृपया दोबारा साइन इन करें, या साइन आउट करके इसे मेहमान के रूप में भेजें।',
      failed: 'यह अभी नहीं भेजा जा सका। कृपया थोड़ी देर में फिर कोशिश करें।',
      unconfigured: 'यह साइट अभी अपने डेटाबेस से जुड़ी नहीं है।',
    },
    optional: 'वैकल्पिक',
    email: 'ईमेल',
    sending: 'भेजा जा रहा है…',
    feedback: {
      sent: {
        title: 'धन्यवाद',
        note: 'आपकी प्रतिक्रिया हमारी टीम तक पहुँच गई है। समीक्षा के बाद यह वेबसाइट पर दिखाई देगी।',
        noteSignedIn: 'आपकी प्रतिक्रिया हमारी टीम तक पहुँच गई है। समीक्षा के बाद यह वेबसाइट पर दिखाई देगी — आप प्रतिक्रिया पेज पर इसकी स्थिति देख सकते हैं।',
        again: 'एक और लिखें',
      },
      invalid: {
        rating: 'एक से पाँच स्टार के बीच रेटिंग चुनें।',
        messageShort: 'कम से कम {n} अक्षर लिखें।',
        messageLong: 'इसे {n} अक्षरों से कम रखें।',
        name: 'वह नाम लिखें जो आपकी प्रतिक्रिया के साथ दिखाया जाए।',
        nameLong: 'नाम {n} अक्षरों से कम रखें।',
        email: 'ऐसा ईमेल पता लिखें जिस पर हम जवाब दे सकें।',
        cityLong: 'शहर का नाम {n} अक्षरों से कम रखें।',
        consent: 'कृपया पुष्टि करें कि आपकी प्रतिक्रिया वेबसाइट पर दिखाई जा सकती है।',
      },
      limit: 'आज आप काफ़ी प्रतिक्रिया भेज चुके हैं — धन्यवाद। कृपया बाकी कल भेजें।',
      about: '“{title}” के बारे में',
      topic: 'यह किस बारे में है?',
      message: 'आपकी प्रतिक्रिया',
      placeholder: 'क्या अच्छा रहा, और क्या बेहतर हो सकता था?',
      left: '{n} अक्षर बाकी',
      over: 'सीमा से {n} ज़्यादा',
      name: 'दिखाया जाने वाला नाम',
      city: 'शहर',
      emailNote: 'कभी नहीं दिखाया जाता — सिर्फ़ जवाब देने के लिए',
      consent: 'समीक्षा के बाद मेरी प्रतिक्रिया ऊपर दिए गए नाम और शहर के साथ इस वेबसाइट पर दिखाई जा सकती है। मेरा ईमेल कभी नहीं दिखाया जाता।',
      send: 'प्रतिक्रिया भेजें',
      account: 'आपके खाते से भेजा गया।',
      guestLead: 'खाते की ज़रूरत नहीं · स्थिति देखने के लिए ',
      guestLink: 'साइन इन करें',
      guestTail: '।',
    },
    article: {
      sent: {
        title: 'लिखने के लिए धन्यवाद',
        noteTo: 'आपका लेख हमारे संपादकों के पास है। अगर यह जर्नल के लिए सही रहा, तो कुछ भी प्रकाशित करने से पहले हम आपको {email} पर लिखेंगे — हम बदलाव सुझा सकते हैं और एक फ़ोटो माँग सकते हैं।',
        noteYou: 'आपका लेख हमारे संपादकों के पास है। अगर यह जर्नल के लिए सही रहा, तो कुछ भी प्रकाशित करने से पहले हम आपको लिखेंगे — हम बदलाव सुझा सकते हैं और एक फ़ोटो माँग सकते हैं।',
        again: 'एक और भेजें',
      },
      invalid: {
        name: 'अपना नाम लिखें, जैसा वह लेख के साथ दिखना चाहिए।',
        email: 'ऐसा ईमेल पता लिखें जिस पर हम जवाब दे सकें।',
        title: 'अपने लेख को एक शीर्षक दें।',
        titleLong: 'शीर्षक {n} अक्षरों से कम रखें।',
        summaryLong: 'सारांश {n} अक्षरों से कम रखें।',
        bodyShort: 'लेख में कम से कम {n} अक्षर होने चाहिए।',
        bodyLong: 'इसे {n} अक्षरों से कम रखें।',
        consent: 'कृपया पुष्टि करें कि यह लेख आपका है और आप इसे साझा कर सकते हैं।',
      },
      limit: 'आज आप तीन लेख भेज चुके हैं — धन्यवाद। कृपया बाकी कल भेजें।',
      about: 'NGD जर्नल के लिए',
      title: 'लेख का शीर्षक',
      summary: 'सारांश',
      summaryNote: 'वैकल्पिक — एक या दो वाक्य',
      body: 'आपका लेख',
      placeholder: 'अपना लेख लिखें या पेस्ट करें। अनुच्छेदों के बीच एक खाली लाइन छोड़ें।',
      wordOne: '{n} शब्द',
      wordMany: '{n} शब्द',
      name: 'आपका नाम',
      emailNote: 'कभी प्रकाशित नहीं होता',
      consent: 'यह लेख मैंने लिखा है, और New Grown Diamond इसे संपादित करके मेरे नाम के साथ अपने जर्नल में प्रकाशित कर सकता है। टीम के मुझसे संपर्क करने से पहले कुछ भी प्रकाशित नहीं होता।',
      send: 'लेख भेजें',
      quiet: 'कुछ भी प्रकाशित होने से पहले हमारे संपादक इसे पढ़ते हैं।',
    },
  },

  gu: {
    topics: {
      general: 'સામાન્ય',
      diamonds: 'હીરા',
      jewellery: 'જ્વેલરી',
      service: 'સેવા',
      website: 'આ વેબસાઇટ',
      journal: 'જર્નલ',
    },
    on: '“{title}” પર',
    stars: {
      shown: '5 માંથી {n}',
      legend: 'તમારું રેટિંગ',
      one: '{n} સ્ટાર — {word}',
      many: '{n} સ્ટાર — {word}',
      words: ['', 'ખરાબ', 'ઠીકઠાક', 'સારું', 'ખૂબ સારું', 'ઉત્તમ'],
      choose: 'રેટિંગ પસંદ કરો',
    },
    errors: {
      email: 'આ ઈમેલ સરનામું સાચું લાગતું નથી. તેને તપાસીને ફરી પ્રયાસ કરો.',
      message: 'કૃપા કરીને થોડું વધુ લખો — ઓછામાં ઓછા 20 અક્ષર.',
      name: 'કૃપા કરીને તમારું નામ લખો.',
      session: 'કૃપા કરીને ફરી સાઇન ઇન કરો, અથવા સાઇન આઉટ કરીને તેને મહેમાન તરીકે મોકલો.',
      failed: 'તે હમણાં મોકલી શકાયું નથી. કૃપા કરીને થોડી વાર પછી ફરી પ્રયાસ કરો.',
      unconfigured: 'આ સાઇટ હાલમાં તેના ડેટાબેઝ સાથે જોડાયેલી નથી.',
    },
    optional: 'વૈકલ્પિક',
    email: 'ઈમેલ',
    sending: 'મોકલાઈ રહ્યું છે…',
    feedback: {
      sent: {
        title: 'આભાર',
        note: 'તમારો પ્રતિસાદ અમારી ટીમ સુધી પહોંચી ગયો છે. સમીક્ષા પછી તે વેબસાઇટ પર દેખાશે.',
        noteSignedIn: 'તમારો પ્રતિસાદ અમારી ટીમ સુધી પહોંચી ગયો છે. સમીક્ષા પછી તે વેબસાઇટ પર દેખાશે — તમે પ્રતિસાદ પેજ પર તેની સ્થિતિ જોઈ શકો છો.',
        again: 'બીજો લખો',
      },
      invalid: {
        rating: 'એકથી પાંચ સ્ટાર વચ્ચે રેટિંગ પસંદ કરો.',
        messageShort: 'ઓછામાં ઓછા {n} અક્ષર લખો.',
        messageLong: 'તેને {n} અક્ષરથી ઓછું રાખો.',
        name: 'તમારા પ્રતિસાદ સાથે બતાવવાનું નામ લખો.',
        nameLong: 'નામ {n} અક્ષરથી ઓછું રાખો.',
        email: 'એવું ઈમેલ સરનામું લખો જેના પર અમે જવાબ આપી શકીએ.',
        cityLong: 'શહેરનું નામ {n} અક્ષરથી ઓછું રાખો.',
        consent: 'કૃપા કરીને ખાતરી આપો કે તમારો પ્રતિસાદ વેબસાઇટ પર બતાવી શકાય.',
      },
      limit: 'આજે તમે ઘણો પ્રતિસાદ મોકલ્યો છે — આભાર. કૃપા કરીને બાકીનો આવતીકાલે મોકલો.',
      about: '“{title}” વિશે',
      topic: 'આ શેના વિશે છે?',
      message: 'તમારો પ્રતિસાદ',
      placeholder: 'શું સારું રહ્યું, અને શું વધુ સારું થઈ શકે?',
      left: '{n} અક્ષર બાકી',
      over: 'મર્યાદા કરતાં {n} વધુ',
      name: 'બતાવવાનું નામ',
      city: 'શહેર',
      emailNote: 'ક્યારેય બતાવાતું નથી — ફક્ત જવાબ આપવા માટે',
      consent: 'સમીક્ષા પછી મારો પ્રતિસાદ ઉપર આપેલા નામ અને શહેર સાથે આ વેબસાઇટ પર બતાવી શકાય છે. મારું ઈમેલ ક્યારેય બતાવાતું નથી.',
      send: 'પ્રતિસાદ મોકલો',
      account: 'તમારા ખાતામાંથી મોકલાયું.',
      guestLead: 'ખાતાની જરૂર નથી · સ્થિતિ જોવા માટે ',
      guestLink: 'સાઇન ઇન કરો',
      guestTail: '.',
    },
    article: {
      sent: {
        title: 'લખવા બદલ આભાર',
        noteTo: 'તમારો લેખ અમારા સંપાદકો પાસે છે. જો તે જર્નલ માટે યોગ્ય હશે, તો કંઈ પણ પ્રકાશિત કરતાં પહેલાં અમે તમને {email} પર લખીશું — અમે ફેરફારો સૂચવી શકીએ અને એક ફોટો માંગી શકીએ.',
        noteYou: 'તમારો લેખ અમારા સંપાદકો પાસે છે. જો તે જર્નલ માટે યોગ્ય હશે, તો કંઈ પણ પ્રકાશિત કરતાં પહેલાં અમે તમને લખીશું — અમે ફેરફારો સૂચવી શકીએ અને એક ફોટો માંગી શકીએ.',
        again: 'બીજો મોકલો',
      },
      invalid: {
        name: 'તમારું નામ લખો, જે રીતે તે લેખ સાથે દેખાવું જોઈએ.',
        email: 'એવું ઈમેલ સરનામું લખો જેના પર અમે જવાબ આપી શકીએ.',
        title: 'તમારા લેખને શીર્ષક આપો.',
        titleLong: 'શીર્ષક {n} અક્ષરથી ઓછું રાખો.',
        summaryLong: 'સારાંશ {n} અક્ષરથી ઓછો રાખો.',
        bodyShort: 'લેખમાં ઓછામાં ઓછા {n} અક્ષર હોવા જોઈએ.',
        bodyLong: 'તેને {n} અક્ષરથી ઓછું રાખો.',
        consent: 'કૃપા કરીને ખાતરી આપો કે આ લેખ તમારો છે અને તમે તેને શેર કરી શકો છો.',
      },
      limit: 'આજે તમે ત્રણ લેખ મોકલ્યા છે — આભાર. કૃપા કરીને બાકીના આવતીકાલે મોકલો.',
      about: 'NGD જર્નલ માટે',
      title: 'લેખનું શીર્ષક',
      summary: 'સારાંશ',
      summaryNote: 'વૈકલ્પિક — એક કે બે વાક્ય',
      body: 'તમારો લેખ',
      placeholder: 'તમારો લેખ લખો અથવા પેસ્ટ કરો. ફકરાઓ વચ્ચે એક ખાલી લાઇન છોડો.',
      wordOne: '{n} શબ્દ',
      wordMany: '{n} શબ્દ',
      name: 'તમારું નામ',
      emailNote: 'ક્યારેય પ્રકાશિત થતું નથી',
      consent: 'આ લેખ મેં લખ્યો છે, અને New Grown Diamond તેમાં ફેરફાર કરીને તેને મારા નામ સાથે પોતાના જર્નલમાં પ્રકાશિત કરી શકે છે. ટીમ મારો સંપર્ક કરે તે પહેલાં કંઈ પણ પ્રકાશિત થતું નથી.',
      send: 'લેખ મોકલો',
      quiet: 'કંઈ પણ પ્રકાશિત થાય તે પહેલાં અમારા સંપાદકો તેને વાંચે છે.',
    },
  },
};
