/**
 * The customer dashboard's words, in the three languages (see
 * src/i18n/useCopy.js). Nav words, "Sign out", "Email", "Account", "Loading…"
 * and "Diamond" come from the site dictionaries.
 *
 * Never translated, and so never here: stock numbers, order and enquiry
 * references, enquiry subjects, shapes, statuses and roles as the database
 * holds them, amounts and currencies, the desk's phone number and email.
 *
 * `tabs` names the five request lists by the keys queries/account.js uses;
 * `requests.empty` is the "No … yet." line for each, worded whole because the
 * word order differs by language. `orderOne` / `orderMany` are the singular
 * and plural; Hindi and Gujarati use one form for both.
 *
 * `welcome.lead` + the first name + `welcome.stop` make the greeting, and
 * `welcome.there` stands in for a name the profile does not have.
 */
export default {
  en: {
    forgotInstead: 'Forgot it and cannot sign in? Use the emailed link instead.',
    nav: { selection: 'Selection', wishlist: 'Wishlist', feedback: 'Feedback' },
    eyebrow: 'Customer dashboard',
    welcome: { lead: 'Welcome back, ', stop: '.', there: 'there' },
    memberSince: 'Member since {date}',
    profile: 'Profile',
    completeness: 'Profile completeness',
    complete: 'Complete. The desk has everything it needs.',
    incomplete: 'Add your details so the desk can reach you faster.',
    glance: 'Your account at a glance',
    loading: 'Loading',
    stats: {
      selection: 'In your selection',
      pricesOnRequest: 'Prices on request',
      nothingYet: 'Nothing added yet',
      saved: 'Saved diamonds',
      onDevice: 'On this device',
      enquiries: 'Enquiries sent',
      toDesk: 'To the diamond desk',
      quotes: 'Quotes received',
      priced: 'Priced by the desk',
      bought: 'Diamonds bought',
      notRecorded: 'Not recorded online',
      spent: 'Total spent',
      confirmed: 'Across confirmed orders',
    },
    orderOne: '{n} order',
    orderMany: '{n} orders',
    purchases: {
      title: 'Purchases',
      loading: 'Loading your orders…',
      unavailable: 'Purchases are not recorded online yet, so this dashboard cannot show what you have bought or spent. Your orders with the desk are unaffected.',
      invoicesLead: 'For invoices or past orders, ',
      whatsapp: 'message the desk on WhatsApp',
      or: ' or ',
      email: 'email us',
      stop: '.',
      error: 'Your orders could not be loaded just now. The rest of your account is unaffected.',
      empty: 'No purchases on your account yet.',
      cols: { order: 'Order', date: 'Date', diamonds: 'Diamonds', status: 'Status', total: 'Total' },
    },
    requests: {
      title: 'Your requests',
      newEnquiry: 'New enquiry',
      types: 'Request types',
      listError: 'This list could not be loaded. The rest of your account is unaffected.',
      empty: {
        enquiries: 'No enquiries yet.',
        quotes: 'No quotes yet.',
        holds: 'No holds yet.',
        inspections: 'No inspections yet.',
        favourites: 'No favourites yet.',
      },
      sendEnquiry: 'Send the desk an enquiry',
      findStone: 'Find a stone',
      jewelleryPiece: 'Jewellery piece',
      lapsed: 'Hold lapsed',
      reservedUntil: 'Reserved until {date}',
      awaitingPrice: 'Awaiting price',
    },
    tabs: {
      enquiries: 'Enquiries',
      quotes: 'Quotes',
      holds: 'Holds',
      inspections: 'Inspections',
      favourites: 'Favourites',
    },
    profileTitle: 'Your profile',
    status: 'Status',
    changePassword: 'Change password',
    secureLink: 'We will email you a secure link.',
    selection: { title: 'Your selection', empty: 'Nothing in your selection yet.', cta: 'Review and request' },
    saved: { title: 'Saved diamonds', empty: 'No saved diamonds yet.', cta: 'Open wishlist' },
    help: { eyebrow: 'The diamond desk', question: 'Questions about a stone, a quote or an order?' },
    mini: { browse: 'Browse diamonds', onRequest: 'On request', more: '+ {n} more', listedValue: 'Listed value' },
  },

  hi: {
    forgotInstead: 'भूल गए हैं और साइन इन नहीं कर पा रहे? तब ईमेल वाले लिंक का उपयोग करें।',
    nav: { selection: 'चयन', wishlist: 'विशलिस्ट', feedback: 'फ़ीडबैक' },
    eyebrow: 'ग्राहक डैशबोर्ड',
    welcome: { lead: 'फिर से स्वागत है, ', stop: '।', there: 'मित्र' },
    memberSince: '{date} से सदस्य',
    profile: 'प्रोफ़ाइल',
    completeness: 'प्रोफ़ाइल कितनी पूरी है',
    complete: 'पूरी हो गई। डेस्क के पास वह सब है जो उसे चाहिए।',
    incomplete: 'अपना विवरण जोड़ें, ताकि डेस्क आप तक जल्दी पहुँच सके।',
    glance: 'एक नज़र में आपका खाता',
    loading: 'लोड हो रहा है',
    stats: {
      selection: 'आपके चयन में',
      pricesOnRequest: 'कीमतें पूछताछ पर',
      nothingYet: 'अभी कुछ नहीं जोड़ा गया',
      saved: 'सहेजे गए हीरे',
      onDevice: 'इसी डिवाइस पर',
      enquiries: 'भेजी गई पूछताछ',
      toDesk: 'डायमंड डेस्क को',
      quotes: 'मिले हुए कोटेशन',
      priced: 'डेस्क द्वारा तय कीमत',
      bought: 'ख़रीदे गए हीरे',
      notRecorded: 'ऑनलाइन दर्ज नहीं',
      spent: 'कुल ख़र्च',
      confirmed: 'सभी पुष्ट ऑर्डर में',
    },
    orderOne: '{n} ऑर्डर',
    orderMany: '{n} ऑर्डर',
    purchases: {
      title: 'ख़रीदारी',
      loading: 'आपके ऑर्डर लोड हो रहे हैं…',
      unavailable: 'ख़रीदारी अभी ऑनलाइन दर्ज नहीं होती, इसलिए यह डैशबोर्ड नहीं दिखा सकता कि आपने क्या ख़रीदा या कितना ख़र्च किया। डेस्क के साथ आपके ऑर्डर पर इसका कोई असर नहीं है।',
      invoicesLead: 'इनवॉइस या पिछले ऑर्डर के लिए, ',
      whatsapp: 'WhatsApp पर डेस्क को मैसेज करें',
      or: ' या ',
      email: 'हमें ईमेल करें',
      stop: '।',
      error: 'आपके ऑर्डर अभी लोड नहीं हो सके। आपके खाते के बाकी हिस्से पर इसका कोई असर नहीं है।',
      empty: 'आपके खाते में अभी कोई ख़रीदारी नहीं है।',
      cols: { order: 'ऑर्डर', date: 'तारीख़', diamonds: 'हीरे', status: 'स्थिति', total: 'कुल' },
    },
    requests: {
      title: 'आपके अनुरोध',
      newEnquiry: 'नई पूछताछ',
      types: 'अनुरोध के प्रकार',
      listError: 'यह सूची लोड नहीं हो सकी। आपके खाते के बाकी हिस्से पर इसका कोई असर नहीं है।',
      empty: {
        enquiries: 'अभी कोई पूछताछ नहीं।',
        quotes: 'अभी कोई कोटेशन नहीं।',
        holds: 'अभी कोई होल्ड नहीं।',
        inspections: 'अभी कोई जाँच नहीं।',
        favourites: 'अभी कोई पसंदीदा नहीं।',
      },
      sendEnquiry: 'डेस्क को पूछताछ भेजें',
      findStone: 'हीरा खोजें',
      jewelleryPiece: 'ज्वेलरी पीस',
      lapsed: 'होल्ड की अवधि खत्म',
      reservedUntil: '{date} तक रिज़र्व',
      awaitingPrice: 'कीमत का इंतज़ार',
    },
    tabs: {
      enquiries: 'पूछताछ',
      quotes: 'कोटेशन',
      holds: 'होल्ड',
      inspections: 'जाँच',
      favourites: 'पसंदीदा',
    },
    profileTitle: 'आपकी प्रोफ़ाइल',
    status: 'स्थिति',
    changePassword: 'पासवर्ड बदलें',
    secureLink: 'हम आपको एक सुरक्षित लिंक ईमेल करेंगे।',
    selection: { title: 'आपका चयन', empty: 'आपके चयन में अभी कुछ नहीं है।', cta: 'देखें और अनुरोध करें' },
    saved: { title: 'सहेजे गए हीरे', empty: 'अभी कोई हीरा सहेजा नहीं गया।', cta: 'विशलिस्ट खोलें' },
    help: { eyebrow: 'डायमंड डेस्क', question: 'किसी हीरे, कोटेशन या ऑर्डर के बारे में सवाल है?' },
    mini: { browse: 'हीरे देखें', onRequest: 'पूछताछ पर', more: '+ {n} और', listedValue: 'सूचीबद्ध मूल्य' },
  },

  gu: {
    forgotInstead: 'ભૂલી ગયા છો અને સાઇન ઇન નથી થઈ શકતું? તો ઈમેલવાળી લિંક વાપરો.',
    nav: { selection: 'પસંદગી', wishlist: 'વિશલિસ્ટ', feedback: 'પ્રતિસાદ' },
    eyebrow: 'ગ્રાહક ડેશબોર્ડ',
    welcome: { lead: 'ફરી સ્વાગત છે, ', stop: '.', there: 'મિત્ર' },
    memberSince: '{date} થી સભ્ય',
    profile: 'પ્રોફાઇલ',
    completeness: 'પ્રોફાઇલ કેટલી પૂર્ણ છે',
    complete: 'પૂર્ણ. ડેસ્ક પાસે જરૂરી બધું જ છે.',
    incomplete: 'તમારી વિગતો ઉમેરો, જેથી ડેસ્ક તમારો ઝડપથી સંપર્ક કરી શકે.',
    glance: 'એક નજરે તમારું ખાતું',
    loading: 'લોડ થઈ રહ્યું છે',
    stats: {
      selection: 'તમારી પસંદગીમાં',
      pricesOnRequest: 'કિંમતો પૂછપરછ પર',
      nothingYet: 'હજી કંઈ ઉમેર્યું નથી',
      saved: 'સાચવેલા હીરા',
      onDevice: 'આ ડિવાઇસ પર',
      enquiries: 'મોકલેલી પૂછપરછ',
      toDesk: 'ડાયમંડ ડેસ્કને',
      quotes: 'મળેલા ક્વોટેશન',
      priced: 'ડેસ્કે નક્કી કરેલી કિંમત',
      bought: 'ખરીદેલા હીરા',
      notRecorded: 'ઓનલાઇન નોંધાયેલું નથી',
      spent: 'કુલ ખર્ચ',
      confirmed: 'પુષ્ટિ થયેલા બધા ઓર્ડરમાં',
    },
    orderOne: '{n} ઓર્ડર',
    orderMany: '{n} ઓર્ડર',
    purchases: {
      title: 'ખરીદી',
      loading: 'તમારા ઓર્ડર લોડ થઈ રહ્યા છે…',
      unavailable: 'ખરીદી હજી ઓનલાઇન નોંધાતી નથી, તેથી આ ડેશબોર્ડ તમે શું ખરીદ્યું કે કેટલો ખર્ચ કર્યો તે બતાવી શકતું નથી. ડેસ્ક સાથેના તમારા ઓર્ડર પર તેની કોઈ અસર નથી.',
      invoicesLead: 'ઇન્વૉઇસ અથવા અગાઉના ઓર્ડર માટે, ',
      whatsapp: 'WhatsApp પર ડેસ્કને મેસેજ કરો',
      or: ' અથવા ',
      email: 'અમને ઈમેલ કરો',
      stop: '.',
      error: 'તમારા ઓર્ડર હમણાં લોડ થઈ શક્યા નથી. તમારા ખાતાના બાકીના ભાગ પર તેની કોઈ અસર નથી.',
      empty: 'તમારા ખાતામાં હજી કોઈ ખરીદી નથી.',
      cols: { order: 'ઓર્ડર', date: 'તારીખ', diamonds: 'હીરા', status: 'સ્થિતિ', total: 'કુલ' },
    },
    requests: {
      title: 'તમારી વિનંતીઓ',
      newEnquiry: 'નવી પૂછપરછ',
      types: 'વિનંતીના પ્રકાર',
      listError: 'આ યાદી લોડ થઈ શકી નથી. તમારા ખાતાના બાકીના ભાગ પર તેની કોઈ અસર નથી.',
      empty: {
        enquiries: 'હજી કોઈ પૂછપરછ નથી.',
        quotes: 'હજી કોઈ ક્વોટેશન નથી.',
        holds: 'હજી કોઈ હોલ્ડ નથી.',
        inspections: 'હજી કોઈ તપાસ નથી.',
        favourites: 'હજી કોઈ મનપસંદ નથી.',
      },
      sendEnquiry: 'ડેસ્કને પૂછપરછ મોકલો',
      findStone: 'હીરો શોધો',
      jewelleryPiece: 'જ્વેલરી પીસ',
      lapsed: 'હોલ્ડની મુદત પૂરી',
      reservedUntil: '{date} સુધી રિઝર્વ',
      awaitingPrice: 'કિંમતની રાહ',
    },
    tabs: {
      enquiries: 'પૂછપરછ',
      quotes: 'ક્વોટેશન',
      holds: 'હોલ્ડ',
      inspections: 'તપાસ',
      favourites: 'મનપસંદ',
    },
    profileTitle: 'તમારી પ્રોફાઇલ',
    status: 'સ્થિતિ',
    changePassword: 'પાસવર્ડ બદલો',
    secureLink: 'અમે તમને એક સુરક્ષિત લિંક ઈમેલ કરીશું.',
    selection: { title: 'તમારી પસંદગી', empty: 'તમારી પસંદગીમાં હજી કંઈ નથી.', cta: 'જુઓ અને વિનંતી કરો' },
    saved: { title: 'સાચવેલા હીરા', empty: 'હજી કોઈ હીરો સાચવ્યો નથી.', cta: 'વિશલિસ્ટ ખોલો' },
    help: { eyebrow: 'ડાયમંડ ડેસ્ક', question: 'કોઈ હીરા, ક્વોટેશન કે ઓર્ડર વિશે પ્રશ્ન છે?' },
    mini: { browse: 'હીરા જુઓ', onRequest: 'પૂછપરછ પર', more: '+ {n} વધુ', listedValue: 'યાદી મુજબ કિંમત' },
  },
};
