import { useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import Reveal from '@/components/motion/Reveal.jsx';
import SplitReveal from '@/components/motion/SplitReveal.jsx';
import ShapeGlyph from '@/components/product/ShapeGlyph.jsx';
import useAsyncData from '@/hooks/useAsyncData.js';
import { fetchDiamond, fetchDiamonds, fetchJewellery, fetchJewelleryPiece } from '@/lib/data/source.js';
import { getSupabase, isSupabaseConfigured } from '@/lib/supabase/client.js';
import styles from './StorePages.module.css';

const chapters = {
  manufacturing: [['01','Seed preparation','A selected seed is cleaned and prepared for a controlled growth run.'],['02','Holder and reactor loading','The seed is positioned before the chamber is sealed.'],['03','Vacuum, gas and plasma','CVD uses a carbon-rich gas and plasma; HPHT uses high pressure and temperature with a carbon source.'],['04','Growth and inspection','Growth is monitored, inspected and repeated only when the real stone requires it.'],['05','Cooling and unloading','The chamber returns to safe conditions before the as-grown material is removed.'],['06','Graphite removal and separation','Residual graphite is removed and the grown material is separated from its seed.'],['07','Scanning and planning','The rough is mapped so cutters can plan yield and proportions.'],['08','Marking and laser shaping','The approved plan guides marking and controlled shaping.'],['09','Bruting and polishing','Facets are established and polished before final inspection and certification.']],
  education: [['01','CVD','Chemical Vapour Deposition grows diamond layer by layer in a carbon-rich plasma.'],['02','HPHT','High Pressure High Temperature recreates a different set of growth conditions.'],['03','The 4Cs','Cut, colour, clarity and carat describe different aspects of a diamond; none should be judged alone.'],['04','Shapes','Round, oval, emerald, pear, cushion and other outlines change the way a stone carries light.'],['05','Certification','An independent grading report records the assessed characteristics of the individual stone.'],['06','Care','Use mild soap, warm water and a soft brush; arrange professional inspection for secure settings.']],
  about: [['01','A Surat perspective','Our story is rooted in the craft and manufacturing culture of Surat.'],['02','Four decades of heritage','Experience informs how we inspect, plan and finish each stone; specific milestones await verified archive material.'],['03','Manufacturing first','We give the growth and finishing process more space than marketing language.'],['04','Made accountable','Inventory, imagery and certificates remain attached to real records rather than invented claims.']],
};

function Intro({ eyebrow, title, lead }) { useEffect(()=>{document.title=`${title} — New Grown Diamond`},[title]); return <header className={styles.hero}><p className={styles.eyebrow}>{eyebrow}</p><SplitReveal as="h1" className={styles.title}>{title}</SplitReveal><Reveal as="p" className={styles.lead}>{lead}</Reveal></header> }
function LoadingGrid(){return <div className={styles.grid}>{[1,2,3].map(i=><div className={styles.skeleton} key={i}/>)}</div>}
function DiamondCard({ row }) { return <Link className={styles.card} to={`/diamonds/${row.public_id}`}><ShapeGlyph className={styles.glyph} shape={row.shape}/><div><div className={styles.meta}><span>{row.stock_number}</span><span>{row.availability}</span></div><h2 className={styles.name}>{row.carat} ct {row.shape}</h2><div className={styles.meta}><span>{row.color} · {row.clarity}</span><span>{row.laboratory}</span></div></div></Link> }

export function DiamondsPage(){const {data,error,loading}=useAsyncData(fetchDiamonds);const [shape,setShape]=useState('All');const rows=useMemo(()=>shape==='All'?(data??[]):(data??[]).filter(x=>x.shape===shape),[data,shape]);return <main id="main" className={styles.page}><div className="ngd-page"><Intro eyebrow="Live inventory" title="Diamonds, held to account." lead="Search the current inventory by the characteristics that matter. Every live record comes from the storefront data source."/><div className={styles.toolbar}><p aria-live="polite">{loading?'Loading':`${rows.length} result${rows.length===1?'':'s'}`}</p><div className={styles.filters}>{['All','Round','Oval','Emerald','Pear'].map(x=><button className={styles.control} aria-pressed={shape===x} onClick={()=>setShape(x)} key={x}>{x}</button>)}</div></div>{loading?<LoadingGrid/>:error?<p className={styles.status}>Inventory could not be loaded. Please try again.</p>:rows.length?<Reveal className={styles.grid} selector="a" stagger={.07}>{rows.map(x=><DiamondCard row={x} key={x.public_id}/>)}</Reveal>:<p className={styles.status}>No stones match this selection.</p>}</div></main>}

export function DiamondDetailPage(){const {publicId}=useParams();const {data,error,loading}=useAsyncData(()=>fetchDiamond(publicId));if(loading)return <main id="main" className={styles.page}><div className="ngd-page"><LoadingGrid/></div></main>;if(error||!data)return <main id="main" className={styles.page}><div className="ngd-page"><Intro eyebrow="Inventory" title="Stone not available." lead="This record may have been reserved, archived or removed."/></div></main>;const specs=[['Stock',data.stock_number],['Carat',data.carat],['Shape',data.shape],['Colour',data.color],['Clarity',data.clarity],['Cut',data.cut],['Growth',data.growth_method],['Laboratory',data.laboratory],['Availability',data.availability]];return <main id="main" className={styles.page}><div className="ngd-page"><Intro eyebrow={data.stock_number} title={`${data.carat} ct ${data.shape}`} lead="A progressive, record-led view of this individual stone."/><section className={styles.detail}><div className={styles.viewer}><ShapeGlyph className={styles.glyph} shape={data.shape}/></div><Reveal className={styles.specs}><h2 className={styles.name}>Stone specification</h2><dl>{specs.map(([k,v])=>v!=null&&<div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>{data.certificate_url&&<a className={styles.control} href={data.certificate_url} target="_blank" rel="noreferrer">View certificate</a>}<Link className={styles.control} to={`/contact?product=${data.public_id}`}>Request a quote</Link></Reveal></section></div></main>}

export function JewelleryPage(){const {data,error,loading}=useAsyncData(fetchJewellery);const [cat,setCat]=useState('All');const cats=['All',...new Set((data??[]).map(x=>x.category))];const rows=cat==='All'?(data??[]):(data??[]).filter(x=>x.category===cat);return <main id="main" className={styles.page}><div className="ngd-page"><Intro eyebrow="The atelier" title="Jewellery, quietly composed." lead="An editorial selection drawn from live product records, with real imagery shown only when supplied."/><div className={styles.toolbar}><p>{rows.length} pieces</p><div className={styles.filters}>{cats.map(x=><button className={styles.control} aria-pressed={cat===x} onClick={()=>setCat(x)} key={x}>{x}</button>)}</div></div>{loading?<LoadingGrid/>:error?<p className={styles.status}>Jewellery could not be loaded.</p>:<Reveal className={styles.grid} selector="a">{rows.map(row=><Link className={styles.card} to={`/jewellery/${row.public_id}`} key={row.public_id}><div className={styles.viewer} aria-label="Real product image required">Media slot</div><div className={styles.meta}><span>{row.category}</span><span>{row.sku}</span></div><h2 className={styles.name}>{row.product_name}</h2><p>{row.short_description}</p></Link>)}</Reveal>}</div></main>}

export function JewelleryDetailPage(){const {publicId}=useParams();const {data,loading}=useAsyncData(()=>fetchJewelleryPiece(publicId));if(loading)return <main id="main" className={styles.page}/>;if(!data)return <main id="main" className={styles.page}><div className="ngd-page"><Intro eyebrow="Atelier" title="Piece not available." lead="No active product record was found."/></div></main>;return <main id="main" className={styles.page}><div className="ngd-page"><Intro eyebrow={data.sku} title={data.product_name} lead={data.short_description||'Product information from the current inventory record.'}/><section className={styles.detail}><div className={styles.viewer}>Real product gallery slot</div><div className={styles.specs}><dl>{[['Category',data.category],['Collection',data.subcategory],['Diamond weight',data.diamond_weight],['Availability',data.availability]].map(([k,v])=>v&&<div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><Link className={styles.control} to={`/contact?product=${data.public_id}`}>Enquire about this piece</Link></div></section></div></main>}

export function StoryPage({kind,title,lead}){return <main id="main" className={styles.page}><div className="ngd-page"><Intro eyebrow={`NGD / ${kind}`} title={title} lead={lead}/><div className={styles.chapters}>{chapters[kind].map(([n,h,p])=><Reveal as="section" className={styles.chapter} key={n}><b>{n}</b><div><h2>{h}</h2><p>{p}</p>{kind==='manufacturing'&&n==='03'&&<div className={styles.status}>Technical media slot — verified factory footage required.</div>}</div></Reveal>)}</div></div></main>}

export function ContactPage(){const [state,setState]=useState('');async function submit(e){e.preventDefault();setState('Sending…');const fd=new FormData(e.currentTarget);if(!isSupabaseConfigured()){setState('Supabase is not configured in this environment. Your message was not sent.');return}try{const {error}=await getSupabase().from('enquiries').insert({name:fd.get('name'),email:fd.get('email'),phone:fd.get('phone'),message:fd.get('message'),enquiry_type:'general'});if(error)throw error;e.currentTarget.reset();setState('Thank you. Your enquiry has been received.')}catch{setState('We could not send your enquiry. Please try again.')}}return <main id="main" className={styles.page}><div className="ngd-page"><Intro eyebrow="Private consultation" title="Begin with a conversation." lead="Tell us what you are looking for. We will respond with real availability and next steps."/><form className={styles.form} onSubmit={submit}><label className={styles.field}>Name<input className={styles.input} name="name" required autoComplete="name"/></label><label className={styles.field}>Email<input className={styles.input} name="email" required type="email" autoComplete="email"/></label><label className={styles.field}>Phone<input className={styles.input} name="phone" autoComplete="tel"/></label><label className={`${styles.field} ${styles.wide}`}>Message<textarea className={styles.textarea} name="message" rows="6" required/></label><button className={styles.control} type="submit">Send enquiry</button><p className={styles.status} aria-live="polite">{state}</p></form></div></main>}

export function AuthPage({mode}){const [state,setState]=useState('');async function submit(e){e.preventDefault();setState('Working…');const fd=new FormData(e.currentTarget);try{const sb=getSupabase();let result;if(mode==='login')result=await sb.auth.signInWithPassword({email:fd.get('email'),password:fd.get('password')});else if(mode==='register')result=await sb.auth.signUp({email:fd.get('email'),password:fd.get('password')});else result=await sb.auth.resetPasswordForEmail(fd.get('email'),{redirectTo:`${location.origin}/reset-password`});if(result.error)throw result.error;setState(mode==='login'?'Signed in.':mode==='register'?'Check your email to confirm your account.':'If an account exists, a recovery email has been sent.')}catch(err){setState(err.message||'Unable to continue.')} }const title=mode==='login'?'Welcome back.':mode==='register'?'Create your account.':'Recover access.';return <main id="main" className={styles.page}><div className={`ngd-page ${styles.auth}`}><Intro eyebrow="Secure account" title={title} lead="A focused, accessible Supabase authentication flow."/><form className={styles.form} onSubmit={submit}><label className={`${styles.field} ${styles.wide}`}>Email<input className={styles.input} type="email" name="email" required autoComplete="email"/></label>{mode!=='forgot'&&<label className={`${styles.field} ${styles.wide}`}>Password<input className={styles.input} type="password" name="password" minLength="8" required autoComplete={mode==='login'?'current-password':'new-password'}/></label>}<button className={styles.control} type="submit">Continue</button><p className={styles.status} aria-live="polite">{state}</p></form></div></main>}

export function DashboardPage({admin=false}){return <main id="main" className={styles.page}><div className="ngd-page"><Intro eyebrow={admin?'Operations':'Your account'} title={admin?'Admin workspace.':'Your diamond desk.'} lead={admin?'Fast access to inventory and customer operations. Role enforcement remains with Supabase RLS.':'Favourites, quotes, holds, inspections and enquiries in one quiet workspace.'}/><div className={styles.dashboard}>{(admin?['Diamonds','Jewellery','Enquiries','Customers','Media','Settings']:['Favourites','Quotes','Holds','Inspections','Enquiries']).map(x=><section className={styles.panel} key={x}><strong>—</strong><h2>{x}</h2><p>Live records appear when the authenticated Supabase project is connected.</p></section>)}</div></div></main>}

export function PolicyPage({title}){return <main id="main" className={styles.page}><div className="ngd-page"><Intro eyebrow="Legal" title={title} lead="This policy must be supplied and approved by New Grown Diamond before publication."/></div></main>}
